### ISSUE TITLE
Program breaks and exit: 

### ISSUE THREAD

**Issue by rafael1138** [s3verus/Click4Coin#1]
Windows 10 PRO Updated.
Python 3.9

Message when breaks:

Traceback (most recent call last):
  File "D:\4coin\main.py", line 176, in <module>
    loop.run_until_complete(main())
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\4coin\main.py", line 160, in main
    await opening_link(username)
  File "D:\4coin\main.py", line 84, in opening_link
    print("waiting for " + timer + " seconds...")
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Rowelabway** [comment]
i get this message on telegram 🙄

⚠️ WARNING: The following is a third party advertisement. Do not trust anything that promises to make you money. Use the following website at your own risk.
---------------------  

BTC Click Bot  

Earn Bitcoin (BTC) by visiting web sites and performing other simple tasks.  
  
---------------------  
Press the "Visit website" button to earn BTC.
You will be redirected to a third party site.
